# -*- coding: utf-8 -*-
"""Rules.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B_CCiw78tWEqRdt3B2WKm8kaem0laBJ7
"""

speciescheck = lambda x:x['Species'] in ("setosa",'versicolor','virginica')
allcheck = lambda x:x['Petal.Length']>0 and x['Petal.Width']>0 and x['Sepal.Width']>0 and x['Sepal.Length']>0
lengthcheck = lambda x:x['Petal.Length']>=2*x['Petal.Width']
sepalcheck = lambda x: x['Sepal.Length']<=30
flowercheck=lambda x:x['Sepal.Length']>x['Petal.Length']
Rules={'speciescheck':speciescheck,'allcheck':allcheck,'lengthcheck':lengthcheck,'sepalcheck':sepalcheck,'flowercheck':flowercheck}