# -*- coding: utf-8 -*-
"""Assignment 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IsLlESSOwtSuO9u-k-iQH4oP84Y28Dcy

# Assignment 3

---
by Arnav Kumar Jain

---

## 1. Consider a 2D list storing student's name along with their marks. Use list comprehension to create another list comprising names of students with  marks greater than 85.
"""

def toppers(L):
    return [i for i in L if i[1]>85]
def main():
    L=eval(input("Enter Marks list: "))
    Toppers=toppers(L)
    print("The list of toppers is:",Toppers)
if __name__=="__main__":
    main()

"""## 2. WAP that takes a list of marks as an input from the user and creates a dictionary storing marks and the corresponding frequency as key-value pairs."""

def frequency(L):
    return dict((i,L.count(i)) for i in L)
def main():
    L=eval(input("Enter Marks list: "))
    print("The dictionary:",frequency(L))
if __name__=="__main__":
    main()

"""## 3. WAP that takes a list of names as an input from the user and creates a dictionary storing word-length as key-value pair for each word given in the list.





"""

def name(L):
    return dict((i,len(i)) for i in L)
def main():
    L=eval(input("Enter names list: "))
    print("The dictionary:",name(L))
if __name__=="__main__":
    main()